# Generated by Django 2.2.6 on 2021-08-01 15:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0005_auto_20210729_1405'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='follow',
            table='db_follow',
        ),
    ]
